# Site settings
title: Surge Velocity, LLC
email: admin@surgevelocity.com
url: https://surgevelocity.github.io
description: "Developing web and mobile apps for the video game industry since 2008."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Surge Velocity LLC
  location: Fort Wayne, IN
  social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nightsurge
  - title: twitter
    url: http://twitter.com/xboxdvr

# Postal address (add as many lines as necessary)
address:
  - line: Fort Wayne, IN

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
